# KEEP ALL GOOGLE PLAY SERVICES (Fixes Blank Banners in Release)
-keep class com.google.android.gms.** { *; }
-keep interface com.google.android.gms.** { *; }
-keep class com.google.ads.** { *; }
-keep interface com.google.ads.** { *; }
-dontwarn com.google.android.gms.**
-dontwarn com.google.ads.**
-keepclassmembers class com.google.android.gms.ads.** { *; }
-keepclassmembers class com.google.ads.mediation.** { *; }
-keep public class com.google.android.gms.ads.AdView
-keep public class com.google.android.gms.ads.AdRequest
-keepattributes *Annotation*
